spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5433}/bookings_db
    username: ${DB_USER:admin}
    password: ${DB_PASS:secret}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
  kafka:
    bootstrap-servers: ${KAFKA_HOST:localhost}:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

server:
  port: 8082

jwt:
  secret: ${JWT_SECRET:polyparrotpolyparrotpolyparrotpolyparrot}

teacher-service:
  url: http://${TEACHER_SERVICE_HOST:localhost}:8081

user-service:
  url: http://${USER_SERVICE_HOST:localhost}:8080

internal:
  secret: ${INTERNAL_SECRET:polyparrot-internal-dev-2026}